-- 1. Create the `cong_van` table
CREATE TABLE IF NOT EXISTS public.cong_van (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    loai_cong_van text, -- 'CV Đi' / 'CV Đến'
    so_hieu text,
    ten_cong_van text,
    noi_dung text,
    co_quan_ban_hanh text,
    ngay_ban_hanh date,
    phan_nhom text,
    file_dinh_kem text, -- Stores the URL or path
    ghi_chu text
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.cong_van ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies for `cong_van` (Full Access for everyone for now, or authenticated)
-- Allow Select for everyone (or authenticated)
CREATE POLICY "Enable read access for all users" ON public.cong_van
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- Allow Insert for everyone (or authenticated)
CREATE POLICY "Enable insert for all users" ON public.cong_van
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);

-- Allow Update for everyone
CREATE POLICY "Enable update for all users" ON public.cong_van
AS PERMISSIVE FOR UPDATE
TO public
USING (true)
WITH CHECK (true);

-- Allow Delete for everyone
CREATE POLICY "Enable delete for all users" ON public.cong_van
AS PERMISSIVE FOR DELETE
TO public
USING (true);

-- 4. Create Storage Bucket `cong_van_file`
insert into storage.buckets (id, name, public)
values ('cong_van_file', 'cong_van_file', true)
on conflict (id) do nothing;

-- 5. Create Storage Policies for `cong_van_file` (Full Access)
-- Policy for SELECT (Download/View)
CREATE POLICY "Give users access to own folder 1ml72a_0" ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'cong_van_file');

-- Policy for INSERT (Upload)
CREATE POLICY "Give users access to own folder 1ml72a_1" ON storage.objects
FOR INSERT
TO public
WITH CHECK (bucket_id = 'cong_van_file');

-- Policy for UPDATE
CREATE POLICY "Give users access to own folder 1ml72a_2" ON storage.objects
FOR UPDATE
TO public
USING (bucket_id = 'cong_van_file');

-- Policy for DELETE
CREATE POLICY "Give users access to own folder 1ml72a_3" ON storage.objects
FOR DELETE
TO public
USING (bucket_id = 'cong_van_file');
