-- Create permissions table
CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role TEXT NOT NULL,
    module TEXT NOT NULL,
    can_view BOOLEAN DEFAULT false,
    can_add BOOLEAN DEFAULT false,
    can_edit BOOLEAN DEFAULT false,
    can_delete BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(role, module)
);

-- RLS Policies (Optional but good practice)
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access to all authenticated users" ON permissions
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow full access to admins" ON permissions
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM users -- Assuming 'users' table exists as per authService, or checking implicit role
            WHERE id = auth.uid() AND (role = 'admin' OR username = 'admin') 
        )
    );
-- Actually for simplicity in this app context w/o strict Auth setup, we allow public read/write or rely on client app logic 
-- since user mentioned 'users' table might be custom.
-- Let's just allow public for now to avoid blocking, as requested in previous turns.
CREATE POLICY "Public Access" ON permissions FOR ALL USING (true) WITH CHECK (true);


-- Seed Data (Insert if not exists)
-- Admin (All permissions)
INSERT INTO permissions (role, module, can_view, can_add, can_edit, can_delete)
SELECT 'admin', m, true, true, true, true
FROM unnest(ARRAY[
    'overview', 'personnel', 'salary', 'work_schedule', 'duty_schedule', 
    'cong_van', 'party', 'absence', 'patient_card', 'settings'
]) AS m
ON CONFLICT (role, module) DO NOTHING;

-- Manager (View all, Edit most, No Delete critical)
INSERT INTO permissions (role, module, can_view, can_add, can_edit, can_delete)
SELECT 'manager', m, true, true, true, false
FROM unnest(ARRAY[
    'overview', 'personnel', 'salary', 'work_schedule', 'duty_schedule', 
    'cong_van', 'party', 'absence', 'patient_card'
]) AS m
ON CONFLICT (role, module) DO NOTHING;

-- Manager Settings (View only)
INSERT INTO permissions (role, module, can_view, can_add, can_edit, can_delete)
VALUES ('manager', 'settings', true, false, false, false)
ON CONFLICT (role, module) DO NOTHING;

-- Staff (View only mostly)
INSERT INTO permissions (role, module, can_view, can_add, can_edit, can_delete)
SELECT 'staff', m, true, false, false, false
FROM unnest(ARRAY[
    'overview', 'personnel', 'salary', 'work_schedule', 'duty_schedule', 
    'cong_van', 'party', 'absence', 'patient_card'
]) AS m
ON CONFLICT (role, module) DO NOTHING;

-- Staff Settings (No access)
INSERT INTO permissions (role, module, can_view, can_add, can_edit, can_delete)
VALUES ('staff', 'settings', false, false, false, false)
ON CONFLICT (role, module) DO NOTHING;
