-- Create table for Card List (Danh mục thẻ)
CREATE TABLE IF NOT EXISTS dm_the_cham (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_the TEXT NOT NULL UNIQUE,
    trang_thai TEXT DEFAULT 'Đã trả thẻ', -- 'Đang mượn thẻ chăm', 'Đã trả thẻ', 'Mất thẻ'
    ghi_chu TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create table for Card Management (Quản lý mượn trả thẻ)
CREATE TABLE IF NOT EXISTS quan_ly_the_cham (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ngay_muon TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    ho_ten_benh_nhan TEXT NOT NULL,
    nam_sinh TEXT,
    ho_ten_nguoi_cham TEXT NOT NULL,
    sdt_nguoi_cham TEXT,
    so_the TEXT NOT NULL, -- References dm_the_cham(so_the) logically
    so_tien_cuoc DECIMAL(15, 2) DEFAULT 500000,
    ghi_chu TEXT,
    nguoi_cho_muon TEXT, -- Stores user's full name or ID
    trang_thai TEXT DEFAULT 'Đang mượn thẻ', -- 'Đang mượn thẻ', 'Đã trả thẻ'
    nguoi_nhan_lai_the TEXT, -- Person who received the return
    ngay_tra TIMESTAMP WITH TIME ZONE, -- Return date and time
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Row Level Security) - Optional but good practice
ALTER TABLE dm_the_cham ENABLE ROW LEVEL SECURITY;
ALTER TABLE quan_ly_the_cham ENABLE ROW LEVEL SECURITY;

-- Policy: Allow all access for public/anon users (Since we use custom auth)
DROP POLICY IF EXISTS "Enable all access for dm_the_cham" ON dm_the_cham;
CREATE POLICY "Enable all access for dm_the_cham" ON dm_the_cham
    FOR ALL
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access for quan_ly_the_cham" ON quan_ly_the_cham;
CREATE POLICY "Enable all access for quan_ly_the_cham" ON quan_ly_the_cham
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Insert initial dummy data for cards
INSERT INTO dm_the_cham (so_the) VALUES 
('THE-001'), ('THE-002'), ('THE-003'), ('THE-004'), ('THE-005')
ON CONFLICT (so_the) DO NOTHING;
