-- Create table for Daily Absences (Quân số nghỉ)
CREATE TABLE IF NOT EXISTS public.quan_so_nghi (
    id bigint generated by default as identity primary key,
    dsnv_id bigint, -- Foreign key to dsnv (not ds_nhan_vien)
    ho_va_ten text not null,
    loai_nghi text not null,
    ngay_nghi date not null default current_date,
    ghi_chu text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Optional: Add constraint if dsnv exists
    CONSTRAINT fk_ds_nhan_vien
      FOREIGN KEY(dsnv_id) 
      REFERENCES public.dsnv(id)
      ON DELETE SET NULL
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_quan_so_nghi_ngay_nghi ON public.quan_so_nghi(ngay_nghi);
CREATE INDEX IF NOT EXISTS idx_quan_so_nghi_dsnv_id ON public.quan_so_nghi(dsnv_id);

-- Enable RLS (Row Level Security) if needed, or leave open for now as per other tables
ALTER TABLE public.quan_so_nghi ENABLE ROW LEVEL SECURITY;

-- Policy to allow all access (adjust as per project security model)
DROP POLICY IF EXISTS "Enable all access for quan_so_nghi" ON public.quan_so_nghi;
CREATE POLICY "Enable all access for quan_so_nghi" ON public.quan_so_nghi
FOR ALL USING (true) WITH CHECK (true);
