-- Create the lich_truc table
CREATE TABLE IF NOT EXISTS public.lich_truc (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ngay_truc date NOT NULL,
    bac_sy text,
    noi_tru text,
    sau_dai_hoc text,
    dieu_duong text, -- Stores multiple names as a comma-separated string or JSON
    phu_dieu_duong text,
    ghi_chu text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.lich_truc ENABLE ROW LEVEL SECURITY;

-- Create Policies
-- Allow authenticated users to view all schedules
CREATE POLICY "Allow authenticated users to select lich_truc" 
ON public.lich_truc FOR SELECT 
TO authenticated 
USING (true);

-- Allow authenticated users to insert schedules
CREATE POLICY "Allow authenticated users to insert lich_truc" 
ON public.lich_truc FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Allow authenticated users to update schedules
CREATE POLICY "Allow authenticated users to update lich_truc" 
ON public.lich_truc FOR UPDATE 
TO authenticated 
USING (true);

-- Allow authenticated users to delete schedules
CREATE POLICY "Allow authenticated users to delete lich_truc" 
ON public.lich_truc FOR DELETE 
TO authenticated 
USING (true);

-- Comment on table
COMMENT ON TABLE public.lich_truc IS 'Bảng quản lý lịch trực bệnh viện';
